### PR TITLE
printing ith Node in linked list.cpp

### PR DESCRIPTION
**Pull request by purohitmansi**
#128

### CODE REVIEW

**Review by purohitmansi — COMMENTED** [review]
@divya520357

**Comment by divya520357** [comment]
why did you output head in issue #128 ?

**Comment by purohitmansi** [comment]
> why did you output head in issue #128 ?

I have output the ith node .

**Comment by purohitmansi** [comment]
> > why did you output head in issue #128 ?
> 
> I have output the ith node .

Please let me known where you found mistake.

**Comment by divya520357** [comment]
@purohitmansi your #127 solution is coreect. you can commit that seperately.

**Comment by purohitmansi** [comment]
> @purohitmansi your #127 solution is coreect. you can commit that seperately.

okayy

**Comment by purohitmansi** [comment]
> @purohitmansi your #127 solution is coreect. you can commit that seperately.

Please guide me how to commit this separately, as it is combined with last ones.

**Comment by divya520357** [comment]
Search for the command git rebase.

**Comment by divya520357** [comment]
And #128 it not running! Send me the ss of the output here.

**Comment by divya520357** [comment]
And #128 it taking way too much time to run! Send me the ss of the output here.

**Comment by purohitmansi** [comment]
Yes, just a minute.

**Comment by purohitmansi** [comment]
> And #128 it taking way too much time to run! Send me the ss of the output
Capture

**Comment by purohitmansi** [comment]
> > @purohitmansi your #127 solution is coreect. you can commit that seperately.
> 
> okayy



> Search for the command git rebase.

I am not able to rebase master branch. Should I add another branch as I am using GitHub Desktop.

**Pull request merged**
