### PR TITLE
Update reverse every word.py

### PR DESCRIPTION
**Pull request by RESHU-05**
error corrected

### CODE REVIEW

**Comment by eeshita19** [comment]
Please make separate PR for different issues

**Comment by RESHU-05** [comment]
I am beginner in this can you please help me how to make two separate PR

**Comment by eeshita19** [comment]
Hy Reshu,
2 separate PRs mean that you need to solve each problem/ issue individually. 
Pick an issue, solve the same and create a PR and then pick another issue and repeat.

**Comment by eeshita19** [comment]
I have merged your PRs for now, next time try and make separate Pull Requests. You can go to our youtube channel to learn how to make PRs.

**Pull request merged**
